"""Updates to users table

Revision ID: ddc95f83385f
Revises: 38b54cfdbd95
Create Date: 2024-05-28 12:25:26.011068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddc95f83385f'
down_revision = '38b54cfdbd95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('places')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_index('name')

    op.drop_table('cities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_index('name')

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('city_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('about', mysql.TEXT(), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.create_index('id', ['id'], unique=True)

    op.create_table('cities',
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('population', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=90), nullable=False),
    sa.Column('weather', mysql.VARCHAR(length=90), nullable=False),
    sa.Column('features', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='cities_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.create_index('id', ['id'], unique=True)

    op.create_table('places',
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('city_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('price', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('details', mysql.TEXT(), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name='places_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    # ### end Alembic commands ###
